# Generated by Django 6.0.7 on 2026-07-22 14:12

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 아이디입니다.'}, help_text='10자 이하로 입력하세요. 문자, 숫자와 @/./+/-/_ 만 사용할 수 있습니다.', max_length=10, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='아이디'),
        ),
    ]
