# Generated by Django 6.0.7 on 2026-07-22 14:24

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shrink_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '이미 사용 중인 아이디입니다.'}, help_text='- 10자 이하<br>- 영문, 숫자와 @/./+/-/_ 만 사용 가능', max_length=10, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='아이디'),
        ),
    ]
