# Generated by Django 6.0.7 on 2026-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_balance_user_balance_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_review',
            field=models.BooleanField(default=False, verbose_name='관리자 검토 대기'),
        ),
    ]
