# Generated by Django 6.0.7 on 2026-07-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='비공개 처리됨'),
        ),
    ]
