# Generated by Django 6.0.7 on 2026-07-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', '거래 전'), ('reserved', '거래 중'), ('sold', '거래 완료')], default='available', max_length=10),
        ),
    ]
