# Generated by Django 6.0.7 on 2026-07-23 15:55

import django.core.validators
import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image_url',
            field=models.ImageField(upload_to=items.models.item_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
