# Generated by Django 6.0.7 on 2026-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_price_alter_itemimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pending_review',
            field=models.BooleanField(default=False, verbose_name='관리자 검토 대기'),
        ),
    ]
