# Generated by Django 6.0.7 on 2026-07-22 14:12

from django.db import migrations

REGION_NAMES = [
    '서울특별시',
    '부산광역시',
    '대구광역시',
    '인천광역시',
    '광주광역시',
    '대전광역시',
    '울산광역시',
    '세종특별자치시',
    '경기도',
    '강원특별자치도',
    '충청북도',
    '충청남도',
    '전북특별자치도',
    '전라남도',
    '경상북도',
    '경상남도',
    '제주특별자치도',
]


def seed_regions(apps, schema_editor):
    Region = apps.get_model('regions', 'Region')
    Region.objects.bulk_create(
        [Region(name=name) for name in REGION_NAMES],
        ignore_conflicts=True,
    )


def remove_regions(apps, schema_editor):
    Region = apps.get_model('regions', 'Region')
    Region.objects.filter(name__in=REGION_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_regions, remove_regions),
    ]
